# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Type_Of_Crime', '0001_initial'),
        ('Thana', '0001_initial'),
        ('Sadar', '0002_auto_20160629_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_no', models.CharField(max_length=50, verbose_name='Case Register Number')),
                ('crime_date', models.DateTimeField(verbose_name='Date of Crime')),
                ('comp_name', models.CharField(max_length=50, verbose_name='Complaiant Name')),
                ('position', geoposition.fields.GeopositionField(default='28.4551918    808319,77.02973962457577', max_length=42, verbose_name='Location of Crime')),
                ('dec', models.TextField(max_length=500, verbose_name='Description')),
                ('sadar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sadar.Sadar')),
                ('thana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Thana.Thana')),
                ('type_crime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Type_Of_Crime.Type_Of_Crime')),
            ],
        ),
    ]
