# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 03:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Crime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='position',
            field=geoposition.fields.GeopositionField(default='28.455191808319,77.02973962457577', max_length=42, verbose_name='Location of Crime'),
        ),
        migrations.AlterField(
            model_name='crime',
            name='sadar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sadar', to='Sadar.Sadar'),
        ),
        migrations.AlterField(
            model_name='crime',
            name='thana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thana', to='Thana.Thana'),
        ),
        migrations.AlterField(
            model_name='crime',
            name='type_crime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_of_crime', to='Type_Of_Crime.Type_Of_Crime'),
        ),
    ]
