# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sadar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sadar',
            name='marker',
            field=models.ImageField(upload_to='Sadar/static/img', verbose_name='Marker'),
        ),
    ]
