# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sadar', '0002_auto_20160629_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sadar',
            name='marker',
            field=models.ImageField(upload_to='static/Sadar/img', verbose_name='Marker'),
        ),
    ]
