# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Type_Of_Crime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type_of_crime',
            name='img',
            field=models.ImageField(upload_to='static/mark', verbose_name='Marker Image'),
        ),
    ]
