# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Thana', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thana',
            name='marker',
            field=models.ImageField(upload_to='static/Thana/img', verbose_name='Marker'),
        ),
    ]
