# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrimeMap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='img',
            field=models.ImageField(upload_to='CrimeMap/static/img', verbose_name='img'),
        ),
    ]
