# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 13:40
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crimemap', '0002_pointofinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='crime',
            name='position',
            field=geoposition.fields.GeopositionField(default='0,0', max_length=42),
        ),
    ]
