# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crimemap', '0003_crime_position'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PointOfInterest',
        ),
        migrations.RemoveField(
            model_name='crime',
            name='loc_lat',
        ),
        migrations.RemoveField(
            model_name='crime',
            name='loc_lon',
        ),
        migrations.AlterField(
            model_name='crime',
            name='case_number',
            field=models.IntegerField(verbose_name='Case Number'),
        ),
        migrations.AlterField(
            model_name='crime',
            name='comp_name',
            field=models.CharField(max_length=200, verbose_name='Complainant Name'),
        ),
        migrations.AlterField(
            model_name='crime',
            name='crime_date',
            field=models.DateTimeField(verbose_name='Date of Crime'),
        ),
        migrations.AlterField(
            model_name='crime',
            name='dec',
            field=models.CharField(max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='crime',
            name='position',
            field=geoposition.fields.GeopositionField(default='28.4594965,77.0266383', max_length=42, verbose_name='Location of Crime'),
        ),
        migrations.AlterField(
            model_name='crime',
            name='type_of_crime',
            field=models.CharField(max_length=200, verbose_name='Type of Crime'),
        ),
    ]
