# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimemap', '0004_auto_20160621_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='dec',
            field=models.TextField(max_length=500, verbose_name='Description'),
        ),
    ]
