# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 13:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crimemap', '0005_auto_20160621_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crime',
            name='type_of_crime',
        ),
    ]
