# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimemap', '0006_remove_crime_type_of_crime'),
    ]

    operations = [
        migrations.AddField(
            model_name='crime',
            name='type_of_crime',
            field=models.CharField(choices=[('t1', 'Test1'), ('t2', 'Test2')], default='t1', max_length=2),
        ),
    ]
