# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimemap', '0007_crime_type_of_crime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='type_of_crime',
            field=models.CharField(choices=[('as', 'Assault'), ('br', 'Burglary'), ('dp', 'Disturbing the Peace'), ('dv', 'Drug Violation'), ('hm', 'Homicide'), ('rb', 'Robbery'), ('th', 'Theft'), ('vd', 'Vandalism'), ('vt', 'Vehicle Theft'), ('ms', 'Miscellaneous')], default='t1', max_length=20, verbose_name='Type Of Crime'),
        ),
    ]
