# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 18:04
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crimemap', '0008_auto_20160621_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='position',
            field=geoposition.fields.GeopositionField(default='28.4551918808319,77.02973962457577', max_length=42, verbose_name='Location of Crime'),
        ),
    ]
