# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimemap', '0009_auto_20160621_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='crime',
            name='name',
            field=models.CharField(default=2, max_length=60),
            preserve_default=False,
        ),
    ]
