# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crimemap', '0010_crime_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crime',
            name='name',
        ),
    ]
