# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimemap', '0011_remove_crime_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crime',
            name='id',
        ),
        migrations.AlterField(
            model_name='crime',
            name='case_number',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Case Number'),
        ),
    ]
