# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimemap', '0012_auto_20160623_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='type_of_crime',
            field=models.CharField(choices=[('Assault', 'Assault'), ('Burglary', 'Burglary'), ('Disturbing the Peace', 'Disturbing the Peace'), ('Drug Violation', 'Drug Violation'), ('Homicide', 'Homicide'), ('Robbery', 'Robbery'), ('Theft', 'Theft'), ('Vandalism', 'Vandalism'), ('Vehicle Theft', 'Vehicle Theft'), ('Miscellaneous', 'Miscellaneous')], default='Assault', max_length=20, verbose_name='Type Of Crime'),
        ),
    ]
