# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimemap', '0014_auto_20160626_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='type_of_crime',
            field=models.CharField(choices=[('Against Children', 'Against Children'), ('Against Women', 'Against Women'), ('Assault', 'Assault'), ('Burglary', 'Burglary'), ('Disturbing the Peace', 'Disturbing the Peace'), ('Drug Violation', 'Drug Violation'), ('Homicide', 'Homicide'), ('Rape', 'Rape'), ('Robbery', 'Robbery'), ('Theft', 'Theft'), ('Vandalism', 'Vandalism'), ('Vehicle Theft', 'Vehicle Theft'), ('Miscellaneous', 'Miscellaneous')], default='Miscellaneous', max_length=20, verbose_name='Type Of Crime'),
        ),
    ]
